[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
serde_json = "1.0"
prost = "0.11"
prost-serde-derive = { path = "../derive" }

[build-dependencies]
tonic-build = { git = "https://github.com/segfault87/tonic", branch = "create-enum-from-str-name" }
