[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.20"
serde = "1.0"
serde_json = "1.0"
prost = "0.12"
prost-serde-derive = { path = "../derive" }

[build-dependencies]
prost-build = "0.12"
tonic-build = "0.11"
