[package]
name = "prost-serde-derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "prost_serde_derive"
proc-macro = true

[dependencies]
convert_case = "0.6"
itertools = "0.10"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
